### ISSUE TITLE
dataset is not avaliable

### ISSUE THREAD

**Issue by yirenheihei** [amikelov/igh_subsets#1]
hi ,I want to ask you a question,I want to learn the BCR analysis as your paper and your data,but the dataset is not avaliable,could you help me ?thank you very much.

**Comment by amikelov** [comment]
Hi!
Sequencing data for the paper have been deposited in the ArrayExpress database (www.ebi.ac.uk/arrayexpress, acc. num. E-MTAB-11193)

I’ve just checked, it is available there. 
Hope this helps.
